FROM ubuntu
MAINTAINER Renato Urajnar

RUN apt-get -qq update
RUN apt-get install -y nginx

RUN rm -rf /etc/nginx/sites-available/default
RUN rm -rf /etc/nginx/sites-enabled/default
ADD nodeapp /etc/nginx/sites-available/nodeapp

RUN ["ln", "-s", "/etc/nginx/sites-available/nodeapp", "/etc/nginx/sites-enabled/nodeapp"]

# Define default command.
CMD ["nginx", "-g", "daemon off;"]